---
- name: Common | Packages
  ansible.builtin.import_tasks: packages.yml
  tags: [common, packages]

- name: Common | Users
  ansible.builtin.import_tasks: users.yml
  when: common_manage_users | bool
  tags: [common, users]

- name: Common | SSH
  ansible.builtin.import_tasks: ssh.yml
  tags: [common, ssh]

- name: Common | MOTD
  ansible.builtin.import_tasks: motd.yml
  when: common_manage_motd | bool
  tags: [common, motd]

- name: Common | PS1
  ansible.builtin.import_tasks: ps1.yml
  tags: [common, ps1]

- name: Common | Debian shell history
  ansible.builtin.import_tasks: history-debian.yml
  when: ansible_facts['distribution'] == 'Debian'
  tags: [common, history]

- name: Common | Sysctl
  ansible.builtin.import_tasks: sysctl.yml
  when: common_sysctl | length > 0
  tags: [common, sysctl]
