---
- name: Common | Install PS1 profile
  ansible.builtin.copy:
    src: ps1.sh
    dest: /etc/profile.d/ps1.sh
    owner: root
    group: root
    mode: '0644'
  when:
    - ansible_facts['distribution'] != 'Debian'
    - common_manage_ps1 | bool

- name: Common | Debian shell prompt
  ansible.builtin.import_tasks: ps1-debian.yml
  when: ansible_facts['distribution'] == 'Debian'
