---
galaxy_info:
  namespace: fredericdelacour      # must be lowercase, no spaces, no dash at ends
  role_name: goldimages_common     # lowercase, letters/numbers/underscore
  author: "Frédéric Delacour"
  description: "Baseline configuration for gold images (packages, users, ssh, motd)."
  license: "MIT"
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions: ["9"]
    - name: Debian
      versions: ["11", "12"]
dependencies: []
