---
galaxy_info:
  namespace: nouil93
  role_name: goldimages_common
  author: "Frédéric Delacour"
  description: "Baseline configuration for GoldImages (packages, users, ssh, motd)."
  license: "MIT"
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
dependencies: []
