---
- name: Converge
  hosts: all
  become: false

  roles:
    - role: common
      common_packages:
        - vim
        - git
      common_packages_redhat:
        - dnf-plugins-core
        - openssh-server
        - procps-ng
      common_packages_debian:
        - apt-utils
      common_timezone: "UTC"
      common_users:
        - name: admin
          groups: sudo
          shell: /bin/bash
          sudo_nopasswd: true
      common_ssh_users:
        - admin
    

