---
galaxy_info:
  author: Frederic DELACOUR
  description: Desktop role

  license: MIT

  min_ansible_version: 2.7

  platforms:
    - name: Centos
      versions:
        - 7
    - name: Fedora
      versions:
        - 31
        - 32

dependencies: []
